export const SAVE_CITY ='SAVE_CITY';
export const SAVE_VENDOR ='SAVE_VENDOR';
export const ADD_ITEM = 'ADD_ITEM';
export const ADD_QUANTITY ='ADD_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const DELETE_ITEM ='DELETE_ITEM';
export const SAVE_USERNAME="SAVE_USERNAME";